### ISSUE TITLE
Check and document package building on RPM based Linux distros

### ISSUE THREAD

**Issue by koppi** [cammill/cammill#28]
Fedora, openSUSE

**Comment by multigcs** [comment]
openSUSE done

**Comment by koppi** [comment]
@multigcs can you update https://github.com/cammill/cammill/wiki/Linux to reflect the packaging and package installing steps?

**Comment by multigcs** [comment]
https://github.com/cammill/cammill/commit/8692afa02def72e326d5ad0ae3fed6c5b1d348f7

**Comment by koppi** [comment]
Fedora ftw!

**Comment by multigcs** [comment]
centos ?
.........................

**Comment by koppi** [comment]
https://getfedora.org/ https://www.centos.org/ CentOS ftw!

**Comment by multigcs** [comment]
Fedora installation is running

**Comment by multigcs** [comment]
ferdora: wtf, das bisher unsympathischste Linux:
Erlauben sie Standort-Abfrage ?
Wollen Sie Ihre Online-Konten verbinden (FB, Goggle, ...) ?

**Comment by multigcs** [comment]
Fedora done 
https://github.com/cammill/cammill/commit/7eb267a5ac8bb433662467cf18768653b8c08cac

**Comment by multigcs** [comment]
hmm, centos DVD-ISO is stalled while boot in KVM :(
i must try the netinstall

**Comment by multigcs** [comment]
the Minimal-ISO is installed now, but without Xorg (i have select Gnome while install !) *grrrrr

**Comment by multigcs** [comment]
after this steps: https://www.centos.org/forums/viewtopic.php?t=47088
i have an gdm login without mouse-curser and than a black window with mouse-curser but no icons, bars or terminals, ctrl-alt-f1 will not work *grrrrrrrrrrrrrr

now, testing live-iso image .......

**Comment by multigcs** [comment]
![download](https://cloud.githubusercontent.com/assets/4227622/8356458/bbc572f0-1b55-11e5-92c0-02d1735232b0.png)
need more download speed :(

**Comment by koppi** [comment]
Here's a list on Wikipedia, if you want em all: https://en.wikipedia.org/wiki/Category:RPM-based_Linux_distributions – If I had a bigger hard drive, I would join the Linux fun, too.

**Comment by koppi** [comment]
For the more popular ARM based distros, I would recommend:

* Debian Wheezy / Jessie on ARM, or
* https://www.raspberrypi.org/downloads/
* http://beagleboard.org/latest-images

**Comment by multigcs** [comment]
i have a Rasperry-PI but i think its to slow for this application.
i will not support ARM at the moment !

i test arch, gentoo, centos and elementaryos now, i think that is more than 
enough

**Comment by multigcs** [comment]
and i will build an simple compile-system like travis for 32/64bit, rpm/deb/tgz/... based on minimal kvm-images.

**Comment by multigcs** [comment]
https://github.com/cammill/cammill/issues/34

**Comment by koppi** [comment]
As http://www.machinekit.io/ is getting more popular, there are more and more ARM users comming, I would recommend that we have at least one ARM target (preferrably Debian/Jessie ARMhf) for testing.

**Comment by multigcs** [comment]
ok, one arm distri (maybe Raspbian) :)

**Comment by multigcs** [comment]
ElementaryOS works (based onUbuntu, no changes needed)

**Comment by multigcs** [comment]
# find packages/ -type f
packages/FreeBSD/10.0/amd64/cammill_0.9_amd64.tgz
packages/FreeBSD/10.1/i386/cammill_0.9_i386.tgz
packages/CentOS/6.6/i386/cammill_0.9-1_i386.rpm
packages/openSUSE_project/13.2/x86_64/cammill_0.9-1_x86_64.rpm
packages/Debian/8.1/i386/cammill_0.9_i386.deb
packages/Debian/8.1/amd64/cammill_0.9_amd64.deb
packages/Windows/MinGW/IA32/cammill_0.9_IA32.exe
packages/Arch-Linux/3.15.5/x86_64/cammill-0.9-1-x86_64.pkg.tar.xz
packages/Ubuntu/14.04/i386/cammill_0.9_i386.deb
packages/Ubuntu/12.04/i386/cammill_0.9_i386.deb
packages/Fedora/20/i686/cammill_0.9-1_i686.rpm
