### ISSUE TITLE
New feature save/restore window positions

### ISSUE THREAD

**Issue by koppi** [cammill/cammill#29]
CAMmill should save/restore the window position between program launches.

**Comment by multigcs** [comment]
https://github.com/cammill/cammill/commit/fdfaf1d1bd4d4b06723e651fe29bf17bd9f70344

**Comment by koppi** [comment]
CAMmill should also remember the maximized state.

**Comment by multigcs** [comment]
maximize will not work correctly :(

(cammill:17342): Gtk-CRITICAL **: IA__gtk_window_maximize: assertion 'GTK_IS_WINDOW (window)' failed

must wait for gtk+3
