### ISSUE TITLE
Check and document package building on Arch Linux

### ISSUE THREAD

**Issue by koppi** [cammill/cammill#30]
See: https://bbs.archlinux.org/viewtopic.php?id=41850

**Comment by multigcs** [comment]
if you can install arch linux you can also install cammill from sources :)

**Comment by koppi** [comment]
:+1:

**Comment by multigcs** [comment]
build is working, now try to build a packages :)

**Comment by multigcs** [comment]
10 targets in makefile now :+1: 
https://stacklet.com/downloads/images/lister/Arch
