### ISSUE TITLE
develop simple compile-farm

### ISSUE THREAD

**Issue by multigcs** [cammill/cammill#34]
based on minimal kvm system images

check git for new commits

	for each supported system

		cp system-image(template) to work-image

		generate build-script > virt-disk/build.sh (install depends, build cammill, test cammill, build package)

		start kvm (work-img + virt-disk)

			template-system boots, check virt-disk for the script

			start the script and write log direct to virt-disk/build.log

			copy package virt-disk/package

			write exit-code to virt-disk/build.done

		check for virt-disk/build.done

		kill kvm

		if build ok

			copy log and package to /packages

			upload packages

			send notify mail

		if not

			send error mail with log

**Comment by koppi** [comment]
:+1:

**Comment by multigcs** [comment]
ElementaryOS works (based onUbuntu, no changes needed)

**Comment by multigcs** [comment]
first tests :)

packages/
packages/FreeBSD
packages/FreeBSD/10.0
packages/FreeBSD/10.0/amd64
packages/FreeBSD/10.0/amd64/cammill_0.9_amd64.tgz
packages/FreeBSD/10.1
packages/FreeBSD/10.1/i386
packages/FreeBSD/10.1/i386/cammill_0.9_i386.tgz
packages/openSUSE_project
packages/openSUSE_project/13.2
packages/openSUSE_project/13.2/x86_64
packages/openSUSE_project/13.2/x86_64/cammill_0.9-1_x86_64.rpm
packages/Debian
packages/Debian/8.1
packages/Debian/8.1/i386
packages/Debian/8.1/i386/cammill_0.9_i386.deb
packages/Debian/8.1/amd64
packages/Debian/8.1/amd64/cammill_0.9_amd64.deb

**Comment by multigcs** [comment]
https://github.com/multigcs/scf

**Comment by multigcs** [comment]
# find packages/ -type f
packages/FreeBSD/10.0/amd64/cammill_0.9_amd64.tgz
packages/FreeBSD/10.1/i386/cammill_0.9_i386.tgz
packages/CentOS/6.6/i386/cammill_0.9-1_i386.rpm
packages/openSUSE_project/13.2/x86_64/cammill_0.9-1_x86_64.rpm
packages/Debian/8.1/i386/cammill_0.9_i386.deb
packages/Debian/8.1/amd64/cammill_0.9_amd64.deb
packages/Windows/MinGW/IA32/cammill_0.9_IA32.exe
packages/Arch-Linux/3.15.5/x86_64/cammill-0.9-1-x86_64.pkg.tar.xz
packages/Ubuntu/14.04/i386/cammill_0.9_i386.deb
packages/Ubuntu/12.04/i386/cammill_0.9_i386.deb
packages/Fedora/20/i686/cammill_0.9-1_i686.rpm
