### ISSUE TITLE
New Feature: support G20 inch units

### ISSUE THREAD

**Issue by koppi** [cammill/cammill#36]
We should add a unit option to the settings somewhere

```
1 inch == 25.4 mm
```

**Comment by multigcs** [comment]
2.54 mm

**Comment by koppi** [comment]
@multigcs sure?

**Comment by multigcs** [comment]
upps :) ne 2.54 cm

**Comment by multigcs** [comment]
https://github.com/cammill/cammill/commit/ce721aa7ab2d0d0fece0d3b20ee7931ea1e7ed6c
