### ISSUE TITLE
Unit selection on DXF load

### ISSUE THREAD

**Issue by WJHildreth** [cammill/cammill#44]
Is it possible to have a selection available when loading a DXF for either inch or mm?  I have a lot of drawings that are in inches.  When they are loaded, they are displayed as mm.  If using the mm -> inch it converts them from what it thinks is mm to inches.  Or at least that is what it looks like to me.  It makes the drawing so small that you cannot manipulate it.

So for example, if I have a drawing that is 24 inches x 48 inches, the program shows it as mm.  Then when I use the tool, mm -> inches, it converts the 24mm to inches (or roughly 1 inch)

Joe

I am running 0.9t17-42 on Ubuntu 14.04 64bit

**Comment by linuxras** [comment]
@WJHildreth When I loaded my models the units were in mm but if I just changed the units in Misc tab it updates without using the convert tool at all.

**Comment by linuxras** [comment]
Guy please make sure that does not break anything.
