### ISSUE TITLE
No date passed to postprocessor.

### ISSUE THREAD

**Issue by onekk** [cammill/cammill#47]
Hello, I'm improving the postprocessor for GRBL and i see that no date is passed tto the postprocessor, in cal.c i see around line 933 that there is  	`postcam_var_push_string("date", "---");`

It appears a great missing that you can't feed the creation date/time in the Gcode output.

TIA and regards

Carlo D.

**Comment by multigcs** [comment]
Linux-Only at the moment
https://github.com/cammill/cammill/commit/9be0f1f854497b77c8601462e38e407bd4bfd617
