### ISSUE TITLE
Can't find the procedure to change the language

### ISSUE THREAD

**Issue by deusyss** [cammill/cammill#49]
Hi,

I'm the french traductor of Cammill. in the first middle of 2015 year, to change lang, we had just to change the cammill.po before compilation.

I see this week, all the good job done since. But i can't find the way to choose the language. Could you explain me please? I saw tonight that french is no complete with the last version.

Thanks

Best regards

**Comment by koppi** [comment]
@deusyss which OS are you running?

**Comment by deusyss** [comment]
Hi, thanks for your quick answer. I'm running Debian like (Linux Mint 17).

**Comment by koppi** [comment]
Does the following from the commandline
```bash
$ LANGUAGE=fr cammill
```
show something like this?
![screenshot from 2015-09-18 22-37-24](https://cloud.githubusercontent.com/assets/9458631/9970525/ead86974-5e55-11e5-9f38-e00f0ffb2dc7.png)

**Comment by deusyss** [comment]
Hi, thanks for this. I tried same thing, but it works only if i previous build a package, install it on my PC.
It's OK. Thank you very much

**Comment by Xav83130** [comment]
Hi,
Same question for Lubuntu ?
Thx
