### ISSUE TITLE
it.po needs an update

### ISSUE THREAD

**Issue by koppi** [cammill/cammill#5]
With https://github.com/cammill/cammill/commit/4a4a920e52b2b6e1f49aadaca7a489c8b81c51d9 two new messages are introduced: msgid "Save Output As.." and msgid "Reload DXF". Please also translate it in it.po. @onekk can you have a look into this?

**Comment by onekk** [comment]
Yes, i can, I'm not very skilled in po files, i can add the two blocks from de.po to it.po an translate them, or i have to use some programs?

Thank you in advance
carlo

**Comment by koppi** [comment]
It's just a text file, so simply add these two blocks in it.po.

**Comment by onekk** [comment]
Italia translation updated and merged.

Regards
Carlo

**Comment by koppi** [comment]
fixed in https://github.com/cammill/cammill/pull/7
