### ISSUE TITLE
Rough / fine milling

### ISSUE THREAD

**Issue by pribossek** [cammill/cammill#61]
When milling thick objects with several passes along the same path, traces of the tool are visible at the edge. For better finish, the milling at several z-levels should be done with a somewhat bigger tool offset, and then followed by a final  cut with an exact tool offset in single pass (without Z-stepping).
Currently, I'm doing this manually, by generating two different paths with different tool offsets and Z-step settings.
Since this is a tedious job, is it possible to add the option to perform roughing and fine milling automatically?

**Comment by multigcs** [comment]
Easy :) but please test first your generated gcode

![cammill](https://cloud.githubusercontent.com/assets/4227622/18311873/1f94858a-7507-11e6-89a1-4286f6ae3ac1.png)
