### ISSUE TITLE
fr.po needs an update

### ISSUE THREAD

**Issue by koppi** [cammill/cammill#9]
With https://github.com/cammill/cammill/commit/4a4a920e52b2b6e1f49aadaca7a489c8b81c51d9 two new messages are introduced: msgid "Save Output As.." and msgid "Reload DXF". Please also translate it in fr.po. @deusyss  can you have a look into this?

**Comment by deusyss** [comment]
Sorry from being late. I do it immediately

**Comment by deusyss** [comment]
Made !!!

**Comment by koppi** [comment]
can you open a pull request to https://github.com/cammill/cammill?

**Comment by deusyss** [comment]
Oups!!! Sorry, i forgot. It's done (i think).

**Comment by koppi** [comment]
Where?

**Comment by deusyss** [comment]
Is it OK, or did i made a pull request on bad repository?

**Comment by koppi** [comment]
I pushed your change to cammill/cammill, see https://github.com/cammill/cammill/commit/12de56fc9024f07042574ce8ad22bf640ec73097
